server:
  port: 8086

spring:
  application:
    name: user-service
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres-users}:${POSTGRES_PORT:5432}/${POSTGRES_DB:smartdrive_users}
    username: ${POSTGRES_USER:smartdrive}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:1}
  
  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME:teamsmartdrive@gmail.com}
    password: ${SMTP_PASSWORD:tilbeticpcdgbzxn}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
  
  # Simplified Security Configuration (no OAuth2 Resource Server)
  # Security is now handled by API Gateway - this service trusts gateway headers

# Gateway Integration - User Service trusts API Gateway for security
auth:
  service:
    internal:
      key: ${INTERNAL_AUTH_KEY:internal-secret-key-2024}

# Gateway signature validation
gateway:
  signature:
    secret: ${GATEWAY_SIGNATURE_SECRET:signature-secret-2024}

# Security settings for infrastructure-first approach
app:
  security:
    gateway-validation:
      enabled: ${GATEWAY_VALIDATION_ENABLED:true}
    signature-validation:
      enabled: ${SIGNATURE_VALIDATION_ENABLED:true}

# User Service Configuration
app:
  user:
    verification:
      token-expiry-hours: 24
      base-url: http://localhost:3000
    password:
      min-length: 8
      require-special-chars: true
      require-numbers: true
      require-uppercase: true
    rate-limiting:
      registration-per-hour: 5
      verification-per-hour: 10
    caching:
      profile-ttl: 3600 # 1 hour
      verification-token-ttl: 86400 # 24 hours
      rate-limit-ttl: 3600 # 1 hour


# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Logging Configuration
logging:
  level:
    com.smartdrive.userservice: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    hostname: user-service
